multitenancy_enabled: false
common:
  storage:
    backend: s3
    s3:
      endpoint: s3.us-gov-west-1.amazonaws.com
      region: us-gov-west-1

blocks_storage:
  storage_prefix: mimirblocks
  s3:
    bucket_name: usas-monitoring-ffa5555d
    sse:
      type: "SSE-S3"

ruler_storage:
  storage_prefix: mimirruler
  s3:
    bucket_name: usas-monitoring-ffa5555d
    sse:
      type: "SSE-S3"

compactor:
  data_dir: /tmp/mimir/compactor
  sharding_ring:
    kvstore:
      store: memberlist

distributor:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist

ingester:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist
    replication_factor: 1

server:
  http_listen_port: 9009
  log_level: debug

store_gateway:
  sharding_ring:
    replication_factor: 1
