---
- hosts: xxxxxxxx

  vars:
    REPO: https://github.com/fedspendingtransparency/usaspending-api.git
    BRANCH: "{{ BRANCH }}"
    CODE_HOME: /data-act/backend

  become_method: sudo

  user: ec2-user
  roles:
  - pull-repo
  - add-hostfile
  tasks:
    - name: update pip
      become: true 
      shell: pip3.5 install --upgrade pip 

    - name: copy requirements.txt (to check for changes)
      become: true 
      copy:
        src:  "{{ CODE_HOME }}/requirements.txt"
        dest: "{{ CODE_HOME }}/requirements_copy.txt"
        remote_src: true
      register: requirements_txt
    - name: install python packages based on requirements.txt
      become: true 
      when: requirements_txt.changed
      pip: chdir="{{ CODE_HOME }}" requirements="requirements.txt" executable=pip3.5

    - name: copy server_requirements.txt (to check for changes)
      become: true 
      copy:
        src:  "{{ CODE_HOME }}/server_requirements.txt"
        dest: "{{ CODE_HOME }}/server_requirements_copy.txt"
        remote_src: true
      register: server_requirements_txt
    - name: install python packages based on server_requirements.txt
      become: true
      when: server_requirements_txt.changed
      pip: chdir="{{ CODE_HOME }}" requirements="server_requirements.txt" executable=pip3.5

    - name: copy legacy_requirements.txt (to check for changes)
      become: true 
      copy:
        src:  "{{ CODE_HOME }}/legacy_requirements.txt"
        dest: "{{ CODE_HOME }}/legacy_requirements_copy.txt"
        remote_src: true
      register: legacy_requirements_txt
    - name: install python packages based on legacy_requirements.txt
      become: true
      when: legacy_requirements_txt.changed
      pip: chdir="{{ CODE_HOME }}" requirements="legacy_requirements.txt" executable=pip2

    - name: ensure the correct directory structure for tmp nginx files
    become: true
    file: 
      path: /var/lib/nginx/tmp
      state: directory
      owner: ec2-user
      mode: "u+wrx"
      recurse: yes
