---

- name: install git
  sudo: true
  yum: name=git
- name: install postgres libraries
  sudo: true
  yum: name=postgresql-devel.x86_64
- name: install gcc
  sudo: true
  yum: name=gcc
- name: install emacs
  sudo: true
  yum: name=emacs
- name: install libffi-devel
  sudo: true
  yum: name=libffi-devel
- name: install python development libraries
  sudo: true
  yum: name=python-devel.x86_64
- name: install the epel repo from a remote repo
  sudo: true
  yum: name=http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm state=present
- name: install nginx
  sudo: true
  yum: name=nginx
- name: install pip
  sudo: true
  yum: name=python-pip
- name: install PCRE for uwsgi
  sudo: true
  yum: name=pcre.x86_64
- name: install PCRE development library
  sudo: true
  yum: name=pcre-devel.x86_64
