# Ansible Galaxy Roles
- src: geerlingguy.repo-epel
  version: 1.3.0
- src: geerlingguy.pip
  version: 1.3.0
- src: geerlingguy.java
  version: 1.10.0
- src: geerlingguy.elasticsearch
  version: 4.2.0
- src: geerlingguy.logstash
  version: 5.1.0
- src: geerlingguy.elasticsearch-curator
  version: 2.1.0
- src: geerlingguy.filebeat
  version: 3.0.2
