---
- name: Checkout backend from git
  sudo: true
  git: repo=https://github.com/fedspendingtransparency/data-act-broker-backend.git version={{ BRANCH }}  dest=/data-act/backend accept_hostkey=true force=yes
- file: path=/data-act owner=ec2-user recurse=yes
  sudo: true