---
- hosts: "{{ HOST }}"

# NOTE: This should run after usaspending-api-image.yml

# Required: {{ BULK_VARS_PREFIX }}, the prefix to the .yml with bulk download vars 
#           AND = the path to the DB URL, either dev or sandbox

  vars:
# Bulk Vars Options: sandbox, dev, staging, prod

    BULK_VARS_PREFIX: "{{ BULK_VARS_PREFIX }}"
    CONFIG_HOME: "/data-act/config"
    CODE_HOME: "/data-act/backend"

  become_method: sudo  

  user: ec2-user
  tasks:  

    - name: Load variables from config repo
      include_vars: /{{ CONFIG_HOME }}/deploy/{{ BULK_VARS_PREFIX }}-bulk-download-vars-ansible.yml

# usaspending_api/settings.py (for running the actual generate download command)

    - name: set up bulk download -> IS_LOCAL = False, S3/SQS/Region
      lineinfile:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: "^IS_LOCAL =.*", 
            line:   "IS_LOCAL = False" }
            
        - { regexp: "^BULK_DOWNLOAD_S3_BUCKET_NAME =.*", 
            line:   "BULK_DOWNLOAD_S3_BUCKET_NAME = '{{ BULK_DOWNLOAD_S3_BUCKET_NAME }}'" }

        - { regexp: "^BULK_DOWNLOAD_SQS_QUEUE_NAME =.*", 
            line:   "BULK_DOWNLOAD_SQS_QUEUE_NAME = '{{ BULK_DOWNLOAD_SQS_QUEUE_NAME }}'" }

        - { regexp: "^BULK_DOWNLOAD_AWS_REGION =.*", 
            line:   "BULK_DOWNLOAD_AWS_REGION = '{{ BULK_DOWNLOAD_AWS_REGION }}'" }

    - name: set ES_HOSTNAME
      lineinfile:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: '\s*ES_HOSTNAME\*=.*'
        line: "ES_HOSTNAME = '{{ ES_HOSTNAME }}'"

    - name: download secrets from S3 bucket
      become: true
      shell: "aws s3 cp s3://da-config/usaspending/{{ BULK_VARS_PREFIX }}-usaspending-api-secrets.yml /etc/ --region us-gov-west-1"

    - name: load secrets (DB_SOURCE)
      include_vars: /etc/{{ BULK_VARS_PREFIX }}-usaspending-api-secrets.yml

# config/filebeat/filebeat.yml

    - name: copy filebeat config
      become: true
      copy:
        src:  "{{ CONFIG_HOME }}/deploy/elk/usaspending_api_filebeat.yml"
        dest: "/etc/filebeat/filebeat.yml"
        remote_src: true

    - name: update filebeat config to set correct index
      become: true
      replace:
        dest: "/etc/filebeat/filebeat.yml"
        regexp: 'index: filebeat'
        replace: "index: usaspending-bd-{{ BULK_VARS_PREFIX }}"


# Start Worker

    - name: enable filebeat service
      become: true
      shell: systemctl enable filebeat

    - name: restart filebeat
      become: true
      shell: systemctl restart filebeat

    - name: stop supervisord
      become: true
      shell: pkill supervisord
      ignore_errors: true

    - name: start supervisord
      become: true
      shell: "supervisord -c {{ CODE_HOME }}/usaspending_api/bulk_download/config/supervisord.conf &"
      environment:
        PYTHONPATH: "{{ CODE_HOME }}"
        NUM_PROCS: "{{ NUM_PROCS }}"
        DATABASE_URL_VAR: "{{ DB_SOURCE }}"
        DOWNLOAD_DATABASE_URL: "{{ DOWNLOAD_DATABASE_URL }}"
      args:
        chdir: "{{ CODE_HOME }}/usaspending_api/"
