---
- shell: setsebool -P httpd_can_network_connect=1
  sudo: true
- shell: pkill supervisord
  sudo: true
  ignore_errors: yes
- shell: supervisord -c /data-act/backend/dataactbroker/config/supervisord.conf &
  sudo: true
  environment:
    PYTHONPATH: "/data-act/backend"
  args:
    chdir: /data-act/backend/dataactbroker/
