---
- shell: setsebool -P httpd_can_network_connect=1
  sudo: true
- shell: supervisord -c /data-act/web-api/dataactbroker/config/supervisord.conf &
  sudo: true
  args:
    chdir: /tmp/src/dataactbroker
