---
- hosts: "{{ HOST }}"

# You MUST provide a DOMAIN_NAME for ALLOWED_HOSTS and SSL

  vars:
    ALLOWED_HOSTS: "{{ ALLOWED_HOSTS }}"

    ## Branch options: sandbox, dev, stg, master
    BRANCH: "{{ BRANCH }}"
    DOMAIN: "{{ DOMAIN }}"

    ## Used only for filebeat: 'envs' is used to translate
    ## BRANCH options above into filebeat.yml index
    envs:
      master: {env_long: prod, env_short: prod}
      stg: {env_long: staging, env_short: stg}
      dev: {env_long: dev, env_short: dev}
      sandbox: {env_long: sandbox, env_short: sbx}

    CODE_HOME: /data-act/backend
    CONFIG_HOME: /data-act/config

    PROD_CACHE_TIMEOUT: None
    NONPROD_CACHE_TIMEOUT: 600

  become_method: sudo

  user: ec2-user

  tasks:
    
    - name: Load variables from config repo
      include_vars: /{{ CONFIG_HOME }}/deploy/{{ BULK_VARS_PREFIX }}-bulk-download-vars-ansible.yml

  # /etc/nginx/nginx.conf

    - name: set nginx configuration path to SSL
      set_fact:
         nginx_path: "{{ CONFIG_HOME }}/deploy/nginx/nginx_usaspending_api.conf"

    - name: (remove later) run nginx as ec2-user
      lineinfile:
        dest: "{{ nginx_path }}"
        regexp: '\s*user.*;'
        line: 'user ec2-user;'

    - name: add server name to nginx config
      lineinfile:
        dest: "{{ nginx_path }}"
        regexp: '\s*server_name.*;'
        line: "\tserver_name {{ DOMAIN }};"

    - name: copy nginx config
      become: true
      copy:
        src:  "{{ nginx_path }}"
        dest: "/etc/nginx/nginx.conf"
        remote_src: true

# config/uwsgi.ini

    - name: duplicate config file to uwsgi_db.ini
      become: true
      copy:
        src:  "{{ CODE_HOME }}/config/uwsgi.ini"
        dest: "{{ CODE_HOME }}/config/uwsgi_db.ini"
        remote_src: true

    - name: download secrets from S3 bucket
      become: true
      shell: " aws s3 cp s3://da-config/usaspending/{{ vars['envs'][BRANCH]['env_long'] }}-usaspending-api-secrets.yml /etc/ --region us-gov-west-1"

    - name: load secrets 
      include_vars: /etc/{{ vars['envs'][BRANCH]['env_long'] }}-usaspending-api-secrets.yml

    - name: add DB_SOURCE to uswgi ini
      become: true
      shell: "echo env=DB_SOURCE={{ DB_SOURCE }} >> {{ CODE_HOME }}/config/uwsgi_db.ini"

    - name: add DB_R1 to uswgi ini
      become: true
      shell: "echo env=DB_R1={{ DB_R1 }} >> {{ CODE_HOME }}/config/uwsgi_db.ini"

# New Relic Settings

    - name: add newrelic label (app_name)
      lineinfile:
        dest: "{{ CODE_HOME }}/config/newrelic.ini"
        regexp: '\s*app_name =.*'
        line: "app_name = usaspending-api-{{ BRANCH }}"
        
    - name: add single-interpreter to uwsgi_db.ini
      become: true
      ini_file:
        dest: "{{ CODE_HOME }}/config/uwsgi_db.ini"
        section: "uwsgi"
        option: single-interpreter
        value: true
        
    - name: modify supervisord configuration (start command)
      ini_file:
        dest: "{{ CODE_HOME }}/config/supervisord.conf"
        section: "program:uwsgi"
        option: command
        value: "newrelic-admin run-program uwsgi --ini /data-act/backend/config/uwsgi_db.ini --socket :3030 --stats /tmp/stats.socket"
        
    - name: modify supervisord configuration (environment)
      ini_file:
        dest: "{{ CODE_HOME }}/config/supervisord.conf"
        section: "program:uwsgi"
        option: environment
        value: "PYTHONPATH=%(ENV_PATH)s:/data-act/backend,NEW_RELIC_CONFIG_FILE={{ CODE_HOME }}/config/newrelic.ini"

 # usaspending_api/settings.py
 
    - name: add bulk download option
      lineinfile:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: '^IS_LOCAL =.*'
        line: "IS_LOCAL = False"
        
    - name: add baby bucket name
      lineinfile:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: '^CSV_S3_BUCKET_NAME =.*'
        line: "CSV_S3_BUCKET_NAME = '{{ CSV_S3_BUCKET_NAME }}'"
        
    - name: add baby sqs name
      lineinfile:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: '^CSV_SQS_QUEUE_NAME =.*'
        line: "CSV_SQS_QUEUE_NAME = '{{ CSV_SQS_QUEUE_NAME }}'"

    - name: add bulk bucket name
      lineinfile:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: '^BULK_DOWNLOAD_S3_BUCKET_NAME =.*'
        line: "BULK_DOWNLOAD_S3_BUCKET_NAME = '{{ BULK_DOWNLOAD_S3_BUCKET_NAME }}'"
        
    - name: add bulk sqs name
      lineinfile:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: '^BULK_DOWNLOAD_SQS_QUEUE_NAME =.*'
        line: "BULK_DOWNLOAD_SQS_QUEUE_NAME = '{{ BULK_DOWNLOAD_SQS_QUEUE_NAME }}'"

    - name: add CSV AWS region
      lineinfile:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: '^CSV_AWS_REGION =.*'
        line: "CSV_AWS_REGION = '{{ CSV_AWS_REGION }}'"

    - name: add Bulk AWS region
      lineinfile:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: '^BULK_DOWNLOAD_AWS_REGION =.*'
        line: "BULK_DOWNLOAD_AWS_REGION = '{{ CSV_AWS_REGION }}'"

    - name: add monthly download bucket
      lineinfile:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: '^MONTHLY_DOWNLOAD_S3_BUCKET_NAME =.*'
        line: "MONTHLY_DOWNLOAD_S3_BUCKET_NAME = '{{ MONTHLY_DOWNLOAD_S3_BUCKET_NAME }}'"

    - name: add static url from s3
      lineinfile:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: '\s*STATIC_URL =.*'
        line: "STATIC_URL = '{{ STATIC_ASSETS_URL }}{{ BRANCH }}/'"

    - name: turn debug off in production or staging
      when: BRANCH == 'master' or BRANCH == 'stg'
      lineinfile:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: '\s*DEBUG =.*'
        line: "DEBUG = False"

    - name: add host to ALLOWED_HOSTS
      lineinfile:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: '\s*ALLOWED_HOSTS =.*'
        line: "ALLOWED_HOSTS = ['{{ ALLOWED_HOSTS }}']"

    - name: enable elasticache (in staging or prod)
      when: BRANCH == 'stg' or BRANCH == 'master'
      lineinfile:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: '\s*CACHE_ENVIRONMENT\s*=.*'
        line: "CACHE_ENVIRONMENT = 'elasticache'"

    - name: replace ELASTICACHE-CONNECTION-STRING (in staging or prod)
      when: BRANCH == 'stg' or BRANCH == 'master'
      replace:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: 'ELASTICACHE-CONNECTION-STRING'
        replace: "{{ ELASTICACHE_URL }}"

    - name: enable local cache (in dev or sandbox)
      when: BRANCH == 'dev' or BRANCH == 'sandbox'
      lineinfile:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: '\s*CACHE_ENVIRONMENT\s*=.*'
        line: "CACHE_ENVIRONMENT = 'local'"

    - name: replace TIMEOUT-IN-SECONDS (in dev or sandbox)
      when: BRANCH == 'dev' or BRANCH == 'sandbox'
      replace:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: 'TIMEOUT-IN-SECONDS'
        replace: "{{ NONPROD_CACHE_TIMEOUT }}"

    - name: replace TIMEOUT-IN-SECONDS (in staging or prod)
      when: BRANCH == 'master' or BRANCH == 'stg'
      replace:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: 'TIMEOUT-IN-SECONDS'
        replace: "{{ PROD_CACHE_TIMEOUT }}"

    - name: add elastic-search endpoint env var (only set up for nonprod)
      when: BRANCH != 'master'
      lineinfile:
        dest: "{{ CODE_HOME }}/usaspending_api/settings.py"
        regexp: '\s*ES_HOSTNAME\*=.*'
        line: "ES_HOSTNAME = '{{ ES_HOSTNAME }}'"

 # SSL Certificates

    - name: copy public.pem from S3 Bucket
      become: true 
      shell: "aws s3 cp s3://usaspending-ssl/usaspending-api-gov/{{ DOMAIN }}/public.pem /etc/cert.pem --region us-gov-west-1"

    - name: copy private.pem from S3 Bucket
      become: true 
      shell: "aws s3 cp s3://usaspending-ssl/usaspending-api-gov/{{ DOMAIN }}/private.pem /etc/cert.key --region us-gov-west-1"
        
 # config/filebeat/filebeat.yml

    - name: copy filebeat config
      become: true
      copy:
        src:  "{{ CONFIG_HOME }}/deploy/elk/filebeat_usaspending_api.yml"
        dest: "/etc/filebeat/filebeat.yml"
        remote_src: true

    - name: update filebeat config to set correct index
      become: true
      replace:
        dest: "/etc/filebeat/filebeat.yml"
        regexp: 'index: filebeat'
        replace: "index: usaspending-api-{{ vars['envs'][BRANCH]['env_short'] }}"

# setup supervisord.service

    - name: make supervisord.service directory
      become: true
      file:
        path: /etc/supervisord/conf.d
        recurse: true
        state: directory

    - name: supervisord.service conf
      become: true
      shell: echo_supervisord_conf > /etc/supervisord/supervisord.conf

    - name: supervisord.service conf.d append
      become: true
      shell: echo "files = conf.d/*.conf" >> /etc/supervisord/supervisord.conf

    - name: supervisord.service copy
      become: true
      copy:
        remote_src: true
        src:  "{{ CONFIG_HOME }}/supervisord.service/supervisord.service"
        dest: "/usr/lib/systemd/system/supervisord.service"

 # start/stop services

    - name: enable newrelic-infra service
      become: true
      shell: systemctl enable newrelic-infra

    - name: restart newrelic-infra service
      become: true
      shell: systemctl restart newrelic-infra

    - name: enable filebeat service
      become: true
      shell: systemctl enable filebeat

    - name: restart filebeat
      become: true
      shell: systemctl restart filebeat

    - name: enable supervisord.service
      become: true
      shell: systemctl enable supervisord

    - name: restart supervisord
      become: true
      shell: systemctl restart supervisord
