# Base Ansible to run on a fresh RHEL7 install.
# Installs USASpending API dependencies that are mutal across environments.

# TODO: This does not include newrelic infrastructure setup
# This does not include the necessary certs and RDS keys to run the API

---
- hosts: "{{ HOST }}"

  become_method: sudo

  user: ec2-user

  tasks:

    - name: upgrade all packages
      become: true
      yum: name=* state=latest

    - name: install EPEL and IUS repos
      become: true
      yum: name={{ item }}
      with_items:
        - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        - https://centos7.iuscommunity.org/ius-release.rpm

    - name: install base dependencies
      become: true
      yum: name={{ item }}
      with_items:
        - ansible
        - gcc
        - gcc-c++
        - git
        - java-1.8.0-openjdk
        - java-1.8.0-openjdk-devel.x86_64
        - libffi-devel
        - libmemcached
        - memcached
        - pcre.x86_64
        - pcre-devel.x86_64
        - postgresql-devel.x86_64
        - python-devel.x86_64
        - python-pip
        - python35u
        - python35u-devel 
        - python35u-libs
        - python35u-pip
        - unzip
        - wget
        - zlib-devel
        - mlocate
        - vim
        - telnet

    - name: install libmemcached-devel (from CentOS repo)
      become: true
      yum: 
        name=http://mirror.centos.org/centos/7/os/x86_64/Packages/libmemcached-devel-1.0.16-5.el7.x86_64.rpm
        
    - name: install nginx (from nginx repo)
      become: true
      yum: 
        name=http://nginx.org/packages/mainline/centos/7/x86_64/RPMS/nginx-1.13.8-1.el7_4.ngx.x86_64.rpm

    - name: install aws cli package
      become: true
      pip: name=awscli executable=pip

    - name: add datadog repository
      become: true
      yum_repository:
        name: Datadog
        description: Datadog Repository 
        baseurl: "https://yum.datadoghq.com/stable/6/x86_64/"
        gpgkey: "https://yum.datadoghq.com/DATADOG_RPM_KEY.public"
      
    - name: clean yum meta-data
      become: true
      command: "yum clean metadata"
      args: 
        warn: no

    - name: install datadog agent 
      become: true
      yum:
        name: datadog-agent
        state: present

    - name: install ddtrace package
      become: true
      pip: name=ddtrace executable=pip3.5

    - name: install filebeat (from filebeat repo)
      become: true
      yum: 
        name=https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.1.1-x86_64.rpm
    
    - name: show timestamp in history (root)
      become: true
      lineinfile: 
        dest: /root/.bash_profile
        line: "export HISTTIMEFORMAT=\"%d/%m/%y %T \""
        state: present

    - name: show timestamp in history (ec2-user)
      lineinfile: 
        dest: /home/ec2-user/.bash_profile
        line: "export HISTTIMEFORMAT=\"%d/%m/%y %T \""
        state: present

    - name: colorize (root)
      become: true
      lineinfile: 
        dest: /root/.bash_profile
        line: 'export PS1="[\[$(tput sgr0)\]\[\033[38;5;1m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]@\[$(tput sgr0)\]\[\033[38;5;45m\]\h\[$(tput sgr0)\]\[\033[38;5;15m\] \W]\\$ \[$(tput sgr0)\]"'
        state: present

    - name: colorize (ec2-user)
      lineinfile:
        dest: /home/ec2-user/.bash_profile
        line: 'export PS1="[\[$(tput sgr0)\]\[\033[38;5;11m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]@\[$(tput sgr0)\]\[\033[38;5;45m\]\h\[$(tput sgr0)\]\[\033[38;5;15m\] \W]\\$ \[$(tput sgr0)\]"'
        state: present

#================================ EOF ========================================#

